### ISSUE TITLE
Assembly instructions 

### ISSUE THREAD

**Issue by harshitgoel96** [HalFrgrd/ErgoDoneCase#1]
How to place the pcb inside the case

**Comment by HalFrgrd** [comment]
The PCB goes in beneath layer 3. It is held in place by the switches which sit on top of layer 3. Since there is a large number of switches and 2 solder points on each one, the PCB is held in place quite well.

**Comment by harshitgoel96** [comment]
Would it be possible for you to make some changes to design to further reduce the design cost? Could you change the  switch plate cutout with Non top removal cutout. And a big rectangle instead of Costar stabilizer. As I want to use Cherry PCB stabilizer

**Comment by HalFrgrd** [comment]
What do you mean by non top removal cutout? Do you mean just not having a switch plate? 
For the stabilisers, yeah I think I will because with Cherry, they are more popular, and you can mount them into the switch plate from the top, so if you already soldered the switches, you can put in the stabs.

**Comment by harshitgoel96** [comment]
The switch plate with perfect square for switches. The one without the space for two clips on both side.

**Comment by HalFrgrd** [comment]
Have a look at this website:
http://builder.swillkb.com/
and get the JSON output from this website: http://www.keyboard-layout-editor.com/
Then select square holes and Cherry stabilisers. This will allow you to get the right sizes for the keyholes and the stabiliser holes. It would take a bit of time to modify the switch plate with these new shapes. 
Feel free to ask me if you're unsure.

**Comment by harshitgoel96** [comment]
i am aware of this. sadly i know nothing about how to modify the file. i lack designing skills

**Comment by harshitgoel96** [comment]
hi. i checked the case and plate builder and pulled the ergodox design from kle, but the switch do not align. can you please confirm if they should align or not ?

**Comment by HalFrgrd** [comment]
Hi, I have added another design that I think is what you want. The design is different from the one KLE but my design fits the PCB's. KLE might need to update their design as I think it is for an older version of the ErgoDox PCB.

**Comment by harshitgoel96** [comment]
hi. 
i see ur updated design.

can you please check one thing ? when i was updating the SVG, i realise that the Costar on each side were like mirror. one would have the wire on right side, other on the left side. but i see the cherry cut out on the same side.

**Comment by harshitgoel96** [comment]
aslo are you using the ergodox pcb to match up the cutouts ?

**Comment by harshitgoel96** [comment]
also i have opened a pull request to update the cut out. its basically is a big square so that only PCB Mount can be used.

**Comment by HalFrgrd** [comment]
I made the case using the acrylic case by Litster.
Thanks for the pull request and I have merged it.

**Comment by harshitgoel96** [comment]
I got the 2 layer version made, and its a really nice fit. I share photos once the build is complete

**Comment by HalFrgrd** [comment]
That's great! Definitely

**Comment by harshitgoel96** [comment]
Hi.
I have assembled the keyboard, it's a perfect fit except a small problem, the cutout for thumb cluster is not big enough, and the  switch do not sit flesh on PCB, they are at an angle due to which the stabs donot fit and the two thumb keys are not sitting quite right.

So I have to fix that. Will update you once I do that.

**Comment by HalFrgrd** [comment]
Ah ok. I haven't had much experience with stabs as I forgot to buy them. That would be great ty.

**Comment by harshitgoel96** [comment]
link to the album :)
https://imgur.com/a/fJbaJ
