### ISSUE TITLE
Printing instructions

### ISSUE THREAD

**Issue by ataquino** [HalFrgrd/ErgoDoneCase#6]
Hello. 

Are the sizes in millimetres? How should I approach printing these?

Thanks.

**Comment by HalFrgrd** [comment]
Hi,

I made these using a laser cutter at a local maker space in Adelaide. Are
you looking to laser cut or 3d print? If you want to laser cut, I don't
really know how to do it myself and I got help at the maker space. I think
it should be straightforward enough if you know someone or have some
instructions on how to use the laser cutter. I think I included how many
layers you need.

Hope this helps,

Feel free to ask any questions, if you're more specific I can probably help
better,

Hal

**Comment by ataquino** [comment]
Yes, I'll laser cut them. But I've decided to try designing my own plates, based off of Ergodox's files. 

Thanks :)
